/**
 * Created by caoyang on 17/3/28.
 */


export const LOAD_OVER = "LOAD_OVER";

// 我要开票

export const LOAD_INVOICING_LIST = "LOAD_INVOICING_LIST";
export const GET_INVOICING_LIST = "GET_INVOICING_LIST";
export const RESET_INVOICING_LIST = "RESET_INVOICING_LIST";


// 我的信息

export const LOAD_PROFILE_LIST = "LOAD_PROFILE_LIST";
export const GET_PROFILE_LIST = "GET_PROFILE_LIST";
export const RESET_PROFILE_LIST = "RESET_PROFILE_LIST";



// 首页

export const LOAD_MAIN_LIST = "LOAD_MAIN_LIST";
export const GET_MAIN_LIST = "GET_MAIN_LIST";
export const RESET_MAIN_LIST = "RESET_MAIN_LIST";

// 发现

export const LOAD_DISCOVERY_LIST = "LOAD_DISCOVERY_LIST";
export const GET_DISCOVERY_LIST = "GET_DISCOVERY_LIST";
export const RESET_DISCOVERY_LIST = "RESET_DISCOVERY_LIST";

// 精选

export const LOAD_CHOICE_GRIL_LIST = "LOAD_CHOICE_GRIL_LIST";
export const GET_CHOICE_GRIL_LIST = "GET_CHOICE_GRIL_LIST";
export const RESET_CHOICE_GRIL_LIST = "RESET_CHOICE_GRIL_LIST";

export const LOAD_CHOICE_BEAUTIFUL_LIST = "LOAD_CHOICE_BEAUTIFUL_LIST";
export const GET_CHOICE_BEAUTIFULL_LIST = "GET_CHOICE_BEAUTIFULL_LIST";
export const RESET_CHOICE_BEAUTIFUL_LIST = "RESET_CHOICE_BEAUTIFUL_LIST";

// 章节列表

export const LOAD_CHAPTER_LIST = "LOAD_CHAPTER_LIST";
export const GET_CHAPTER_LIST = "GET_CHAPTER_LIST";
export const RESET_CHAPTER_LIST = "RESET_CHAPTER_LIST";

// 漫画详情

export const LOAD_COMBICK_DETIAL_LIST = "LOAD_COMBICK_DETIAL_LIST";
export const GET_COMBICK_DETIAL_LIST = "GET_COMBICK_DETIAL_LIST";
export const RESET_COMBICK_DETIAL_LIST = "RESET_COMBICK_DETIAL_LIST";

// 收藏

export const LOAD_COLLECTION_LIST = "LOAD_COLLECTION_LIST";
export const GET_COLLECTION_LIST = "GET_COLLECTION_LIST";
export const RESET_COLLECTION_LIST = "RESET_COLLECTION_LIST";

